language: python
python:
    - "3.4"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install pillow
    - pip install matplotlib
script:
    - cd gui
    - coverage run tests.py
after_success:
    - coveralls
