# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(897, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 41, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.leftLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.leftLayout.setContentsMargins(0, 0, 0, 0)
        self.leftLayout.setObjectName("leftLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(740, 0, 160, 591))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.rightLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.rightLayout.setContentsMargins(0, 0, 0, 0)
        self.rightLayout.setObjectName("rightLayout")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(46, 2, 691, 581))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 897, 21))
        self.menubar.setObjectName("menubar")
        self.menuPlik = QtWidgets.QMenu(self.menubar)
        self.menuPlik.setObjectName("menuPlik")
        self.menuFiltry = QtWidgets.QMenu(self.menubar)
        self.menuFiltry.setObjectName("menuFiltry")
        self.menuSzum = QtWidgets.QMenu(self.menuFiltry)
        self.menuSzum.setObjectName("menuSzum")
        self.menuInne = QtWidgets.QMenu(self.menuFiltry)
        self.menuInne.setObjectName("menuInne")
        self.menuTransformacja = QtWidgets.QMenu(self.menubar)
        self.menuTransformacja.setObjectName("menuTransformacja")
        self.menuDopasowania = QtWidgets.QMenu(self.menubar)
        self.menuDopasowania.setObjectName("menuDopasowania")
        self.menuHistogram = QtWidgets.QMenu(self.menuDopasowania)
        self.menuHistogram.setObjectName("menuHistogram")
        self.menuWstawianie = QtWidgets.QMenu(self.menubar)
        self.menuWstawianie.setObjectName("menuWstawianie")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOtw_rz = QtWidgets.QAction(MainWindow)
        self.actionOtw_rz.setObjectName("actionOtw_rz")
        self.actionZako_cz = QtWidgets.QAction(MainWindow)
        self.actionZako_cz.setObjectName("actionZako_cz")
        self.actionNowy = QtWidgets.QAction(MainWindow)
        self.actionNowy.setObjectName("actionNowy")
        self.actionG_rnoprzepustowy = QtWidgets.QAction(MainWindow)
        self.actionG_rnoprzepustowy.setObjectName("actionG_rnoprzepustowy")
        self.actionDolnoprzepustowy = QtWidgets.QAction(MainWindow)
        self.actionDolnoprzepustowy.setObjectName("actionDolnoprzepustowy")
        self.actionWyostrzanie = QtWidgets.QAction(MainWindow)
        self.actionWyostrzanie.setObjectName("actionWyostrzanie")
        self.actionRozmywanie = QtWidgets.QAction(MainWindow)
        self.actionRozmywanie.setObjectName("actionRozmywanie")
        self.actionUsuwanie_szumu_i_ziarna = QtWidgets.QAction(MainWindow)
        self.actionUsuwanie_szumu_i_ziarna.setObjectName("actionUsuwanie_szumu_i_ziarna")
        self.actionZaszumianie = QtWidgets.QAction(MainWindow)
        self.actionZaszumianie.setObjectName("actionZaszumianie")
        self.actionG_rnoprzepustowy_2 = QtWidgets.QAction(MainWindow)
        self.actionG_rnoprzepustowy_2.setObjectName("actionG_rnoprzepustowy_2")
        self.actionDolnoprzepustowy_2 = QtWidgets.QAction(MainWindow)
        self.actionDolnoprzepustowy_2.setObjectName("actionDolnoprzepustowy_2")
        self.actionWykrywanie_kraw_dzi = QtWidgets.QAction(MainWindow)
        self.actionWykrywanie_kraw_dzi.setObjectName("actionWykrywanie_kraw_dzi")
        self.actionZaznaczanie = QtWidgets.QAction(MainWindow)
        self.actionZaznaczanie.setObjectName("actionZaznaczanie")
        self.actionObr_t = QtWidgets.QAction(MainWindow)
        self.actionObr_t.setObjectName("actionObr_t")
        self.actionSkalowanie = QtWidgets.QAction(MainWindow)
        self.actionSkalowanie.setObjectName("actionSkalowanie")
        self.actionKadrowanie = QtWidgets.QAction(MainWindow)
        self.actionKadrowanie.setObjectName("actionKadrowanie")
        self.actionJasno = QtWidgets.QAction(MainWindow)
        self.actionJasno.setObjectName("actionJasno")
        self.actionKontrast = QtWidgets.QAction(MainWindow)
        self.actionKontrast.setObjectName("actionKontrast")
        self.actionNasycenie = QtWidgets.QAction(MainWindow)
        self.actionNasycenie.setObjectName("actionNasycenie")
        self.actionGamma = QtWidgets.QAction(MainWindow)
        self.actionGamma.setObjectName("actionGamma")
        self.actionOdwr_kolory = QtWidgets.QAction(MainWindow)
        self.actionOdwr_kolory.setObjectName("actionOdwr_kolory")
        self.actionProgowanie = QtWidgets.QAction(MainWindow)
        self.actionProgowanie.setObjectName("actionProgowanie")
        self.actionPodgl_d = QtWidgets.QAction(MainWindow)
        self.actionPodgl_d.setObjectName("actionPodgl_d")
        self.actionNormalizacja = QtWidgets.QAction(MainWindow)
        self.actionNormalizacja.setObjectName("actionNormalizacja")
        self.actionTekst = QtWidgets.QAction(MainWindow)
        self.actionTekst.setObjectName("actionTekst")
        self.actionKolor = QtWidgets.QAction(MainWindow)
        self.actionKolor.setObjectName("actionKolor")
        self.actionWype_nianie = QtWidgets.QAction(MainWindow)
        self.actionWype_nianie.setObjectName("actionWype_nianie")
        self.actionZapisz = QtWidgets.QAction(MainWindow)
        self.actionZapisz.setObjectName("actionZapisz")
        self.actionZapisz_jako = QtWidgets.QAction(MainWindow)
        self.actionZapisz_jako.setObjectName("actionZapisz_jako")
        self.menuPlik.addAction(self.actionNowy)
        self.menuPlik.addAction(self.actionOtw_rz)
        self.menuPlik.addAction(self.actionZapisz)
        self.menuPlik.addAction(self.actionZapisz_jako)
        self.menuPlik.addAction(self.actionZako_cz)
        self.menuSzum.addAction(self.actionUsuwanie_szumu_i_ziarna)
        self.menuSzum.addAction(self.actionZaszumianie)
        self.menuInne.addAction(self.actionG_rnoprzepustowy_2)
        self.menuInne.addAction(self.actionDolnoprzepustowy_2)
        self.menuInne.addAction(self.actionProgowanie)
        self.menuFiltry.addAction(self.actionWyostrzanie)
        self.menuFiltry.addAction(self.actionRozmywanie)
        self.menuFiltry.addAction(self.actionWykrywanie_kraw_dzi)
        self.menuFiltry.addAction(self.menuSzum.menuAction())
        self.menuFiltry.addAction(self.menuInne.menuAction())
        self.menuTransformacja.addAction(self.actionZaznaczanie)
        self.menuTransformacja.addAction(self.actionObr_t)
        self.menuTransformacja.addAction(self.actionSkalowanie)
        self.menuTransformacja.addAction(self.actionKadrowanie)
        self.menuHistogram.addAction(self.actionPodgl_d)
        self.menuHistogram.addAction(self.actionNormalizacja)
        self.menuDopasowania.addAction(self.actionJasno)
        self.menuDopasowania.addAction(self.actionKontrast)
        self.menuDopasowania.addAction(self.actionNasycenie)
        self.menuDopasowania.addAction(self.actionGamma)
        self.menuDopasowania.addAction(self.actionOdwr_kolory)
        self.menuDopasowania.addAction(self.menuHistogram.menuAction())
        self.menuDopasowania.addAction(self.actionKolor)
        self.menuDopasowania.addAction(self.actionWype_nianie)
        self.menuWstawianie.addAction(self.actionTekst)
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.menuFiltry.menuAction())
        self.menubar.addAction(self.menuTransformacja.menuAction())
        self.menubar.addAction(self.menuDopasowania.menuAction())
        self.menubar.addAction(self.menuWstawianie.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PITE - Projekt"))
        self.menuPlik.setTitle(_translate("MainWindow", "Plik"))
        self.menuFiltry.setTitle(_translate("MainWindow", "Filtr"))
        self.menuSzum.setTitle(_translate("MainWindow", "Szum"))
        self.menuInne.setTitle(_translate("MainWindow", "Inne"))
        self.menuTransformacja.setTitle(_translate("MainWindow", "Transformacja"))
        self.menuDopasowania.setTitle(_translate("MainWindow", "Dopasowania"))
        self.menuHistogram.setTitle(_translate("MainWindow", "Histogram"))
        self.menuWstawianie.setTitle(_translate("MainWindow", "Wstawianie"))
        self.actionOtw_rz.setText(_translate("MainWindow", "Otwórz..."))
        self.actionZako_cz.setText(_translate("MainWindow", "Zakończ"))
        self.actionNowy.setText(_translate("MainWindow", "Nowy"))
        self.actionG_rnoprzepustowy.setText(_translate("MainWindow", "Górnoprzepustowy"))
        self.actionDolnoprzepustowy.setText(_translate("MainWindow", "Dolnoprzepustowy"))
        self.actionWyostrzanie.setText(_translate("MainWindow", "Wyostrzanie"))
        self.actionRozmywanie.setText(_translate("MainWindow", "Rozmywanie"))
        self.actionUsuwanie_szumu_i_ziarna.setText(_translate("MainWindow", "Usuwanie szumu i ziarna"))
        self.actionZaszumianie.setText(_translate("MainWindow", "Zaszumianie"))
        self.actionG_rnoprzepustowy_2.setText(_translate("MainWindow", "Górnoprzepustowy"))
        self.actionDolnoprzepustowy_2.setText(_translate("MainWindow", "Dolnoprzepustowy"))
        self.actionWykrywanie_kraw_dzi.setText(_translate("MainWindow", "Wykrywanie krawędzi"))
        self.actionZaznaczanie.setText(_translate("MainWindow", "Zaznaczanie"))
        self.actionObr_t.setText(_translate("MainWindow", "Obrót"))
        self.actionSkalowanie.setText(_translate("MainWindow", "Skalowanie"))
        self.actionKadrowanie.setText(_translate("MainWindow", "Kadrowanie"))
        self.actionJasno.setText(_translate("MainWindow", "Jasność"))
        self.actionKontrast.setText(_translate("MainWindow", "Kontrast"))
        self.actionNasycenie.setText(_translate("MainWindow", "Nasycenie"))
        self.actionGamma.setText(_translate("MainWindow", "Gamma"))
        self.actionOdwr_kolory.setText(_translate("MainWindow", "Odwróć kolory"))
        self.actionProgowanie.setText(_translate("MainWindow", "Progowanie"))
        self.actionPodgl_d.setText(_translate("MainWindow", "Podgląd"))
        self.actionNormalizacja.setText(_translate("MainWindow", "Normalizacja"))
        self.actionTekst.setText(_translate("MainWindow", "Tekst"))
        self.actionKolor.setText(_translate("MainWindow", "Kolor (Pipeta)"))
        self.actionWype_nianie.setText(_translate("MainWindow", "Wypełnianie"))
        self.actionZapisz.setText(_translate("MainWindow", "Zapisz"))
        self.actionZapisz_jako.setText(_translate("MainWindow", "Zapisz jako..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

